from typing import List as _py_List
from typing import ClassVar as _py_ClassVar
import cern.cmw.directory.client
import cern.japc.core
import cern.japc.core.factory
import cern.japc.core.spi.factory
import java.util


class CcdbServiceConfigLookup(cern.japc.core.spi.factory.ServiceConfigLookup):
    def __init__(self): ...
    def getConfig(self, string: str) -> _py_List[java.util.Properties]: ...

class CcdbServiceNameResolver(cern.japc.core.factory.ServiceNameResolver):
    SYSPROP_JAPC_CCDB_SERVICE_NAME_RESOLVER_DISABLED: _py_ClassVar[str] = ...
    def __init__(self): ...
    def getServiceName(self, string: str, parameterDescriptor: cern.japc.core.ParameterDescriptor) -> str: ...

class DirectoryLocator:
    def __init__(self): ...
    @classmethod
    def get(cls) -> cern.cmw.directory.client.DirectoryClient: ...

class ServiceBinder:
    def __init__(self): ...
    @classmethod
    def bind(cls, properties: java.util.Properties) -> None: ...
    @classmethod
    def main(cls, stringArray: _py_List[str]) -> None: ...
    @classmethod
    def update(cls, serverInfo: cern.cmw.directory.client.ServerInfo) -> None: ...
