import org.slf4j


class MBean:
    def getDescription(self) -> str: ...

class MBeanRegistry:
    def __init__(self): ...
    @staticmethod
    def get() -> 'MBeanRegistry': ...
    def getMBean(self, string: str) -> MBean: ...
    def registerMBean(self, string: str, mBean: MBean, logger: org.slf4j.Logger) -> None: ...
    def setJmxAppName(self, string: str) -> None: ...
    def unregisterAll(self, logger: org.slf4j.Logger) -> None: ...
    def unregisterMBean(self, string: str, logger: org.slf4j.Logger) -> None: ...
