import cern.japc.core
import cern.japc.core.factory
import cern.japc.core.spi
import cern.japc.core.spi.cache
import cern.japc.core.spi.factory
import cern.japc.core.spi.group
import cern.japc.core.spi.subscription
import cern.japc.core.transaction
import cern.japc.value
import java.io
import java.util
import typing


class CompositeParameterCreatorImpl(cern.japc.core.spi.factory.CompositeParameterCreator):
    def __init__(self, map: typing.Union[java.util.Map[str, 'CompositeParameterStructure'], typing.Mapping[str, 'CompositeParameterStructure']]): ...
    @typing.overload
    def createParameter(self, parameterUrl: cern.japc.core.spi.ParameterUrl, parameterDescriptor: cern.japc.core.ParameterDescriptor, valueDescriptor: cern.japc.value.ValueDescriptor, parameterFactory: cern.japc.core.factory.ParameterFactory) -> cern.japc.core.transaction.TransactionalParameter: ...
    @typing.overload
    def createParameter(self, parameterUrl: cern.japc.core.spi.ParameterUrl, parameterDescriptor: cern.japc.core.ParameterDescriptor, valueDescriptor: cern.japc.value.ValueDescriptor, parameterFactory: cern.japc.core.factory.ParameterFactory, internalParameterCharacteristics: cern.japc.core.spi.factory.InternalParameterCharacteristics) -> cern.japc.core.transaction.TransactionalParameter: ...
    def isKnownCompositeParameter(self, parameterUrl: cern.japc.core.spi.ParameterUrl) -> bool: ...

class CompositeParameterStructure:
    @typing.overload
    def __init__(self, stringArray: typing.List[str], object: typing.Any): ...
    @typing.overload
    def __init__(self, stringArray: typing.List[str], object: typing.Any, groupSubscriptionStrategyFactory: cern.japc.core.spi.group.GroupSubscriptionStrategyFactory): ...
    def getAdapter(self) -> typing.Any: ...
    def getComponents(self) -> typing.List[str]: ...
    def getGroupingStrategyFactory(self) -> cern.japc.core.spi.group.GroupSubscriptionStrategyFactory: ...
    def setGroupingStrategyFactory(self, groupSubscriptionStrategyFactory: cern.japc.core.spi.group.GroupSubscriptionStrategyFactory) -> None: ...

class ParameterCreatorConfigurationManager:
    def getConfig(self, parameterCreatorId: 'ParameterCreatorId') -> java.util.Properties: ...

class ParameterCreatorId(java.io.Serializable):
    def __init__(self, string: str, string2: str): ...
    def equals(self, object: typing.Any) -> bool: ...
    def getProtocol(self) -> str: ...
    def getServiceName(self) -> str: ...
    def hashCode(self) -> int: ...
    def isProtocolDefined(self) -> bool: ...
    def toString(self) -> str: ...

class ParameterMetaFactory(cern.japc.core.factory.ParameterFactory, cern.japc.core.factory.ParameterMetaFactoryConstants):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, serviceNameResolverArray: typing.List[cern.japc.core.factory.ServiceNameResolver], serviceConfigLookupArray: typing.List[cern.japc.core.spi.factory.ServiceConfigLookup]): ...
    @typing.overload
    def __init__(self, serviceNameResolverArray: typing.List[cern.japc.core.factory.ServiceNameResolver], serviceConfigLookupArray: typing.List[cern.japc.core.spi.factory.ServiceConfigLookup], string: str, string2: str): ...
    def registerInParameterFactory(self) -> None: ...
    def setCompositeParameterCreator(self, compositeParameterCreator: cern.japc.core.spi.factory.CompositeParameterCreator) -> None: ...
    def setWildcardSelectorResolver(self, wildcardSelectorResolver: cern.japc.core.spi.subscription.WildcardSelectorResolver) -> None: ...

class ParameterCreatorConfigurationManagerImpl(ParameterCreatorConfigurationManager, cern.japc.core.spi.cache.JapcCache):
    def __init__(self, serviceConfigLookupArray: typing.List[cern.japc.core.spi.factory.ServiceConfigLookup]): ...
    def clearAll(self) -> None: ...
    def getConfig(self, parameterCreatorId: ParameterCreatorId) -> java.util.Properties: ...
    def toString(self) -> str: ...
