import cern.rbac.common
import cern.rbac.common.authorization
import java.lang
import java.util
import typing


class AbstractRequest(java.lang.Cloneable):
    def __init__(self): ...
    def clone(self) -> typing.Any: ...
    def getParameters(self) -> java.util.Map['RequestParameterType', typing.Any]: ...
    def getRequestType(self) -> 'RequestType': ...
    def getVersion(self) -> str: ...
    def isVerbose(self) -> bool: ...
    def toString(self) -> str: ...

class AccessMapCommand(java.lang.Enum['AccessMapCommand']):
    MAPS_FOR_SERVER: typing.ClassVar['AccessMapCommand'] = ...
    MAPS_FOR_CLASS: typing.ClassVar['AccessMapCommand'] = ...
    MAPS_FOR_CLASS_TEST: typing.ClassVar['AccessMapCommand'] = ...
    MAPS_FOR_FRONT_END: typing.ClassVar['AccessMapCommand'] = ...
    @staticmethod
    def fromString(string: str) -> 'AccessMapCommand': ...
    def getBunchSize(self) -> int: ...
    def getName(self) -> str: ...
    def getScriptName(self) -> str: ...
    def toString(self) -> str: ...
    _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(string: str) -> 'AccessMapCommand': ...
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
    @staticmethod
    def values() -> typing.List['AccessMapCommand']: ...

_RequestBuilder__Request = typing.TypeVar('_RequestBuilder__Request', bound=AbstractRequest)  # <Request>
class RequestBuilder(typing.Generic[_RequestBuilder__Request]):
    def __init__(self, request: _RequestBuilder__Request): ...
    def addParameters(self, map: typing.Union[java.util.Map['RequestParameterType', typing.Any], typing.Mapping['RequestParameterType', typing.Any]]) -> None: ...
    def buildRequest(self) -> _RequestBuilder__Request: ...
    def setRequestType(self, requestType: 'RequestType') -> None: ...
    def setVerbose(self, boolean: bool) -> 'RequestBuilder'[_RequestBuilder__Request]: ...
    def setVersion(self, string: str) -> 'RequestBuilder'[_RequestBuilder__Request]: ...

class RequestParameterType(java.lang.Enum['RequestParameterType']):
    SERVER_ADDR_SUFFIX: typing.ClassVar['RequestParameterType'] = ...
    APPLICATION: typing.ClassVar['RequestParameterType'] = ...
    APPLICATION_ID: typing.ClassVar['RequestParameterType'] = ...
    TOKEN_FORMAT: typing.ClassVar['RequestParameterType'] = ...
    TOKEN_TYPE: typing.ClassVar['RequestParameterType'] = ...
    LIFETIME: typing.ClassVar['RequestParameterType'] = ...
    ACCOUNT_NAME: typing.ClassVar['RequestParameterType'] = ...
    USER_NAME: typing.ClassVar['RequestParameterType'] = ...
    PASSWORD: typing.ClassVar['RequestParameterType'] = ...
    ORIGIN: typing.ClassVar['RequestParameterType'] = ...
    ROLE: typing.ClassVar['RequestParameterType'] = ...
    TOKEN: typing.ClassVar['RequestParameterType'] = ...
    SIGN_BUFFER: typing.ClassVar['RequestParameterType'] = ...
    VERBOSE: typing.ClassVar['RequestParameterType'] = ...
    BUILD: typing.ClassVar['RequestParameterType'] = ...
    PARAMETER: typing.ClassVar['RequestParameterType'] = ...
    CLASS: typing.ClassVar['RequestParameterType'] = ...
    DEVICE: typing.ClassVar['RequestParameterType'] = ...
    PROPERTY: typing.ClassVar['RequestParameterType'] = ...
    OPERATION: typing.ClassVar['RequestParameterType'] = ...
    MCS_ROLE: typing.ClassVar['RequestParameterType'] = ...
    VERSION: typing.ClassVar['RequestParameterType'] = ...
    SAML_RESPONSE: typing.ClassVar['RequestParameterType'] = ...
    OAUTH_ACCESS_TOKEN: typing.ClassVar['RequestParameterType'] = ...
    KRB5_TICKET: typing.ClassVar['RequestParameterType'] = ...
    CHECKING_POLICY: typing.ClassVar['RequestParameterType'] = ...
    @staticmethod
    def fromString(string: str) -> 'RequestParameterType': ...
    def getName(self) -> str: ...
    _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(string: str) -> 'RequestParameterType': ...
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
    @staticmethod
    def values() -> typing.List['RequestParameterType']: ...
    class ParameterTypeConstants:
        SERVER_ADDR_SUFFIX_CONSTANT: typing.ClassVar[str] = ...
        APPLICATION_CONSTANT: typing.ClassVar[str] = ...
        APPLICATION_ID_CONSTANT: typing.ClassVar[str] = ...
        TOKEN_FORMAT_CONSTANT: typing.ClassVar[str] = ...
        TOKEN_TYPE_CONSTANT: typing.ClassVar[str] = ...
        LIFETIME_CONSTANT: typing.ClassVar[str] = ...
        ACCOUNT_NAME_CONSTANT: typing.ClassVar[str] = ...
        USER_NAME_CONSTANT: typing.ClassVar[str] = ...
        PASSWORD_CONSTANT: typing.ClassVar[str] = ...
        ORIGIN_CONSTANT: typing.ClassVar[str] = ...
        ROLE_CONSTANT: typing.ClassVar[str] = ...
        TOKEN_CONSTANT: typing.ClassVar[str] = ...
        SIGN_BUFFER_CONSTANT: typing.ClassVar[str] = ...
        VERBOSE_CONSTANT: typing.ClassVar[str] = ...
        BUILD_CONSTANT: typing.ClassVar[str] = ...
        PARAMETER_CONSTANT: typing.ClassVar[str] = ...
        CLASS_CONSTANT: typing.ClassVar[str] = ...
        DEVICE_CONSTANT: typing.ClassVar[str] = ...
        PROPERTY_CONSTANT: typing.ClassVar[str] = ...
        OPERATION_CONSTANT: typing.ClassVar[str] = ...
        MCS_ROLE_CONSTANT: typing.ClassVar[str] = ...
        VERSION_CONSTANT: typing.ClassVar[str] = ...
        SAML_RESPONSE_CONSTANT: typing.ClassVar[str] = ...
        OAUTH_ACCESS_TOKEN_CONSTANT: typing.ClassVar[str] = ...
        KRB5_TICKET_CONSTANT: typing.ClassVar[str] = ...
        CHECKING_POLICY_CONSTANT: typing.ClassVar[str] = ...
        def __init__(self, requestParameterType: 'RequestParameterType'): ...

class RequestType(java.lang.Enum['RequestType']):
    AUTHENTICATE_EXPLICIT: typing.ClassVar['RequestType'] = ...
    AUTHENTICATE_LOCATION: typing.ClassVar['RequestType'] = ...
    AUTHENTICATE_KERBEROS: typing.ClassVar['RequestType'] = ...
    AUTHENTICATE_SAML: typing.ClassVar['RequestType'] = ...
    AUTHENTICATE_OAUTH: typing.ClassVar['RequestType'] = ...
    AUTHENTICATE_RENEWAL: typing.ClassVar['RequestType'] = ...
    CHECK_ACCESS: typing.ClassVar['RequestType'] = ...
    GENERATE_MAP: typing.ClassVar['RequestType'] = ...
    MCS_ROLE: typing.ClassVar['RequestType'] = ...
    MCS_PUBLIC_KEY: typing.ClassVar['RequestType'] = ...
    MCS_SIGN: typing.ClassVar['RequestType'] = ...
    @staticmethod
    def fromUri(string: str) -> 'RequestType': ...
    def getUri(self) -> str: ...
    _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(string: str) -> 'RequestType': ...
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
    @staticmethod
    def values() -> typing.List['RequestType']: ...
    class UriConstants:
        AUTHENTICATE_EXPLICIT_URI: typing.ClassVar[str] = ...
        AUTHENTICATE_LOCATION_URI: typing.ClassVar[str] = ...
        AUTHENTICATE_KERBEROS_URI: typing.ClassVar[str] = ...
        AUTHENTICATE_SAML_URI: typing.ClassVar[str] = ...
        AUTHENTICATE_OAUTH_URI: typing.ClassVar[str] = ...
        AUTHENTICATE_RENEWAL_URI: typing.ClassVar[str] = ...
        CHECK_ACCESS_URI: typing.ClassVar[str] = ...
        GENERATE_MAP_URI: typing.ClassVar[str] = ...
        MCS_ROLE_URI: typing.ClassVar[str] = ...
        MCS_PUBLIC_KEY_URI: typing.ClassVar[str] = ...
        MCS_SIGN_URI: typing.ClassVar[str] = ...

class ServerErrorCode(java.lang.Enum['ServerErrorCode']):
    BAD_REQUEST: typing.ClassVar['ServerErrorCode'] = ...
    AUTHENTICATION_FAILED: typing.ClassVar['ServerErrorCode'] = ...
    PROCESSING_ERROR: typing.ClassVar['ServerErrorCode'] = ...
    @staticmethod
    def fromInt(int: int) -> 'ServerErrorCode': ...
    def getCode(self) -> int: ...
    _valueOf_1__T = typing.TypeVar('_valueOf_1__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(string: str) -> 'ServerErrorCode': ...
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_1__T], string: str) -> _valueOf_1__T: ...
    @staticmethod
    def values() -> typing.List['ServerErrorCode']: ...

class AccessCheckerRequest(AbstractRequest):
    def __init__(self): ...
    def getCheckingPolicy(self) -> cern.rbac.common.authorization.CheckingPolicy: ...
    def getDevice(self) -> str: ...
    def getDeviceClass(self) -> str: ...
    def getOperation(self) -> cern.rbac.common.authorization.Operation: ...
    def getProperty(self) -> str: ...
    def getToken(self) -> cern.rbac.common.RbaToken: ...

class AccessCheckerRequestBuilder(RequestBuilder[AccessCheckerRequest]):
    def buildRequest(self) -> AccessCheckerRequest: ...
    @staticmethod
    def newInstance() -> 'AccessCheckerRequestBuilder': ...
    def setCheckingPolicy(self, checkingPolicy: cern.rbac.common.authorization.CheckingPolicy) -> 'AccessCheckerRequestBuilder': ...
    def setDevice(self, string: str) -> 'AccessCheckerRequestBuilder': ...
    def setDeviceClass(self, string: str) -> 'AccessCheckerRequestBuilder': ...
    def setOperation(self, operation: cern.rbac.common.authorization.Operation) -> 'AccessCheckerRequestBuilder': ...
    def setProperty(self, string: str) -> 'AccessCheckerRequestBuilder': ...
    def setToken(self, rbaToken: cern.rbac.common.RbaToken) -> 'AccessCheckerRequestBuilder': ...

class AccessMapRequest(AbstractRequest):
    def __init__(self): ...
    def getCommand(self) -> AccessMapCommand: ...
    def getParameter(self) -> str: ...
    def getToken(self) -> cern.rbac.common.RbaToken: ...

class AccessMapRequestBuilder(RequestBuilder[AccessMapRequest]):
    def buildRequest(self) -> AccessMapRequest: ...
    @staticmethod
    def newInstance() -> 'AccessMapRequestBuilder': ...
    def setCommand(self, accessMapCommand: AccessMapCommand) -> 'AccessMapRequestBuilder': ...
    def setParameter(self, string: str) -> 'AccessMapRequestBuilder': ...
    def setToken(self, rbaToken: cern.rbac.common.RbaToken) -> 'AccessMapRequestBuilder': ...

class AuthenticationRequest(AbstractRequest):
    def __init__(self): ...
    def getAccountName(self) -> str: ...
    def getApplication(self) -> str: ...
    def getKerberosTicket(self) -> str: ...
    def getLifetime(self) -> int: ...
    def getOauthAccessToken(self) -> str: ...
    def getOrigin(self) -> cern.rbac.common.RbaToken: ...
    def getPassword(self) -> str: ...
    def getRoles(self) -> typing.List[str]: ...
    def getSamlResponse(self) -> str: ...
    def getTokenType(self) -> cern.rbac.common.TokenType: ...
    def getUserName(self) -> str: ...

class AuthenticationRequestBuilder(RequestBuilder[AuthenticationRequest]):
    @staticmethod
    def newInstance() -> 'AuthenticationRequestBuilder': ...
    def setAccountName(self, string: str) -> 'AuthenticationRequestBuilder': ...
    def setApplication(self, string: str) -> 'AuthenticationRequestBuilder': ...
    def setKerberosTicket(self, byteArray: typing.List[int]) -> 'AuthenticationRequestBuilder': ...
    def setLifetime(self, int: int) -> 'AuthenticationRequestBuilder': ...
    def setOauthAccessToken(self, string: str) -> 'AuthenticationRequestBuilder': ...
    def setOrigin(self, rbaToken: cern.rbac.common.RbaToken) -> 'AuthenticationRequestBuilder': ...
    def setPassword(self, string: str) -> 'AuthenticationRequestBuilder': ...
    def setRoles(self, stringArray: typing.List[str]) -> 'AuthenticationRequestBuilder': ...
    def setSamlResponse(self, string: str) -> 'AuthenticationRequestBuilder': ...
    def setTokenType(self, tokenType: cern.rbac.common.TokenType) -> 'AuthenticationRequestBuilder': ...
    def setUserName(self, string: str) -> 'AuthenticationRequestBuilder': ...

class McsKeyRequest(AbstractRequest):
    def __init__(self): ...
    def getDevice(self) -> str: ...
    def getDeviceClass(self) -> str: ...
    def getMCSRole(self) -> str: ...
    def getProperty(self) -> str: ...

class McsKeyRequestBuilder(RequestBuilder[McsKeyRequest]):
    def buildRequest(self) -> McsKeyRequest: ...
    @staticmethod
    def newInstance() -> 'McsKeyRequestBuilder': ...
    def setDevice(self, string: str) -> 'McsKeyRequestBuilder': ...
    def setDeviceClass(self, string: str) -> 'McsKeyRequestBuilder': ...
    def setMCSRole(self, string: str) -> 'McsKeyRequestBuilder': ...
    def setProperty(self, string: str) -> 'McsKeyRequestBuilder': ...

class McsRoleRequest(AbstractRequest):
    @typing.overload
    def __init__(self, string: str, string2: str, string3: str): ...
    @typing.overload
    def __init__(self, map: typing.Union[java.util.Map[RequestParameterType, typing.Any], typing.Mapping[RequestParameterType, typing.Any]]): ...
    def getDevice(self) -> str: ...
    def getDeviceClass(self) -> str: ...
    def getProperty(self) -> str: ...

class McsSignRequest(AbstractRequest):
    def __init__(self): ...
    def getSignBuffer(self) -> typing.List[int]: ...
    def getToken(self) -> cern.rbac.common.RbaToken: ...

class McsSignRequestBuilder(RequestBuilder[McsSignRequest]):
    def buildRequest(self) -> McsSignRequest: ...
    @staticmethod
    def newInstance() -> 'McsSignRequestBuilder': ...
    def setSignBuffer(self, byteArray: typing.List[int]) -> 'McsSignRequestBuilder': ...
    def setToken(self, rbaToken: cern.rbac.common.RbaToken) -> 'McsSignRequestBuilder': ...

class AccessCheckerRequestImpl(AccessCheckerRequest):
    def __init__(self): ...

class AccessMapRequestImpl(AccessMapRequest):
    def __init__(self): ...
    def setCommand(self, accessMapCommand: AccessMapCommand) -> None: ...
    def setParameter(self, string: str) -> None: ...
    def setToken(self, rbaToken: cern.rbac.common.RbaToken) -> None: ...

class McsKeyRequestImpl(McsKeyRequest):
    def __init__(self): ...

class McsSignRequestImpl(McsSignRequest):
    def __init__(self): ...
