from typing import ClassVar as _py_ClassVar
import cern.accsoft.commons.diag
import cern.accsoft.commons.diag.matcher
import java.lang


class AbstractJapcThrowableMatcher(cern.accsoft.commons.diag.matcher.StringThrowableMatcher):
    JAPC_PROBLEM_DOMAIN: _py_ClassVar[str] = ...

class JapcParamExExceptionThrowableMatcher(cern.accsoft.commons.diag.matcher.ExceptionClassThrowableMatcher):
    JAPC_PE_EX_MATCHER_NAME: _py_ClassVar[str] = ...
    def __init__(self): ...

class JapcParamExProxyThrowableMatcher(cern.accsoft.commons.diag.matcher.ProxyThrowableMatcher):
    def __init__(self): ...

class JapcThrowableMessageComposer(cern.accsoft.commons.diag.DefaultThrowableMessageComposer):
    def __init__(self): ...
    def composeMessage(self, throwable: java.lang.Throwable) -> str: ...

class JapcCmwDisconnectedStringThrowableMatcher(AbstractJapcThrowableMatcher):
    CMW_DISCONNECTED_MATCHER_NAME: _py_ClassVar[str] = ...
    def __init__(self): ...

class JapcCmwRdaParameterCreatorStringThrowableMatcher(AbstractJapcThrowableMatcher):
    CMW_RDA_PARAMETER_CREATOR_MATCHER_NAME: _py_ClassVar[str] = ...
    def __init__(self): ...

class JapcNoValueStringThrowableMatcher(AbstractJapcThrowableMatcher):
    JAPC_NO_VALUE_MATCHER_NAME: _py_ClassVar[str] = ...
    def __init__(self): ...

class JapcParamExFgcErrorStringThrowableMatcher(AbstractJapcThrowableMatcher):
    JAPC_FGC_ERROR_MATCHER_NAME: _py_ClassVar[str] = ...
    def __init__(self): ...

class JapcParamExMonitoringNotSupportedStringThrowableMatcher(AbstractJapcThrowableMatcher):
    JAPC_MONITORING_NOT_SUPORTED_MATCHER_NAME: _py_ClassVar[str] = ...
    def __init__(self): ...

class JapcParamExNoSubscriptionStringThrowableMatcher(AbstractJapcThrowableMatcher):
    JAPC_PE_SUB_FAIL_MATCHER_NAME: _py_ClassVar[str] = ...
    def __init__(self): ...

class JapcParamExStringThrowableMatcher(AbstractJapcThrowableMatcher):
    JAPC_PE_MATCHER_NAME: _py_ClassVar[str] = ...
    def __init__(self): ...

class JapcParamRuntimeExStringThrowableMatcher(AbstractJapcThrowableMatcher):
    JAPC_RUNTIME_MATCHER_NAME: _py_ClassVar[str] = ...
    def __init__(self): ...

class JapcThrowableMatcher(AbstractJapcThrowableMatcher):
    JAPC_MATCHER_NAME: _py_ClassVar[str] = ...
    def __init__(self): ...
