import cern.accsoft.commons.tracing.requests
import java.util


class ClientRequestInfoStatistics:
    def __init__(self, string: str): ...
    def add(self, clientRequestInfo: cern.accsoft.commons.tracing.requests.ClientRequestInfo) -> None: ...
    def getElaspedTimeMaxMillis(self) -> int: ...
    def getElaspedTimeMeanMillis(self) -> int: ...
    def getElaspedTimeMinMillis(self) -> int: ...
    def getElaspedTimeSumMillis(self) -> int: ...
    def getElaspedTimeSumSquare(self) -> int: ...
    def getExceptionsCount(self) -> int: ...
    def getFirstRequestFinishTimeMillis(self) -> int: ...
    def getKey(self) -> str: ...
    def getLastRequestFinishTime(self) -> java.util.Date: ...
    def getLastRequestFinishTimeMillis(self) -> int: ...
    def getRequestsCount(self) -> int: ...

class ClientRequestInfoStatisticsMap(java.util.HashMap[str, ClientRequestInfoStatistics]):
    def __init__(self): ...
    def add(self, clientRequestInfo: cern.accsoft.commons.tracing.requests.ClientRequestInfo) -> None: ...
    def getSize(self) -> int: ...
    def getStartTimeMillis(self) -> int: ...
    def getStats(self) -> java.util.Collection[ClientRequestInfoStatistics]: ...

class StatisticsFile:
    def __init__(self, string: str): ...
    def appendStats(self, clientRequestInfoStatistics: ClientRequestInfoStatistics) -> None: ...
    def getFileName(self) -> str: ...
    def write(self) -> None: ...
