import cern.japc.core
import cern.japc.value
import cern.lsa.client.common.japc
import cern.lsa.domain.settings
import java.io


class LsaSelectorImpl(cern.lsa.client.common.japc.LsaSelector, java.io.Serializable):
    def __init__(self, selector: cern.japc.core.Selector, settingPartEnum: cern.lsa.domain.settings.SettingPartEnum, string: str): ...
    def getDataFilter(self) -> cern.japc.value.ParameterValue: ...
    def getId(self) -> str: ...
    def getPeriod(self) -> int: ...
    def getSettingPart(self) -> cern.lsa.domain.settings.SettingPartEnum: ...
    def getTrimDescription(self) -> str: ...
    def isPeriodic(self) -> bool: ...
