from typing import ClassVar as _py_ClassVar
import cern.accsoft.commons.diag.matcher
import java.lang


class AbstractCmwConfigStringThrowableMatcher(cern.accsoft.commons.diag.matcher.StringThrowableMatcher):
    CMW_CONFIG_DOMAIN: _py_ClassVar[str] = ...
    CMW_HINT_URL: _py_ClassVar[str] = ...
    CMW_CONTACT_URL: _py_ClassVar[str] = ...

class AbstractCmwFEStringThrowableMatcher(cern.accsoft.commons.diag.matcher.StringThrowableMatcher):
    CMW_HW_PROBLEM_DOMAIN: _py_ClassVar[str] = ...
    CMW_HINT_STRING: _py_ClassVar[str] = ...
    CMW_HINT_URL: _py_ClassVar[str] = ...
    CMW_CONTACT_URL: _py_ClassVar[str] = ...
    def checkMatching(self, throwable: java.lang.Throwable) -> java.lang.Throwable: ...

class AbstractCmwStringThrowableMatcher(cern.accsoft.commons.diag.matcher.StringThrowableMatcher):
    CMW_PROBLEM_DOMAIN: _py_ClassVar[str] = ...
    CMW_HINT_URL: _py_ClassVar[str] = ...
    CMW_CONTACT_URL: _py_ClassVar[str] = ...

class AbstractCmw3ServerExceptionStringThrowableMatcher(AbstractCmwFEStringThrowableMatcher): ...

class Cmw3InvalidArgumentStringThrowableMatcher(AbstractCmwConfigStringThrowableMatcher):
    CMW_INVALID_ARGUMENT_MATCHER_NAME: _py_ClassVar[str] = ...
    def __init__(self): ...

class Cmw3NameServiceExceptionStringThrowableMatcher(AbstractCmwFEStringThrowableMatcher):
    CMW_NAME_SERVICE_MATCHER_NAME: _py_ClassVar[str] = ...
    def __init__(self): ...

class Cmw3TransportExceptionStringThrowableMatcher(AbstractCmwFEStringThrowableMatcher):
    CMW_TRANSPORT_EXCEPTION_MATCHER_NAME: _py_ClassVar[str] = ...
    HINT_URL: _py_ClassVar[str] = ...
    def __init__(self): ...

class CmwNamingServerStringThrowableMatcher(AbstractCmwConfigStringThrowableMatcher):
    CMW_NAMING_SERVE_MATCHER_NAME: _py_ClassVar[str] = ...
    def __init__(self): ...

class CmwStringThrowableMatcher(AbstractCmwStringThrowableMatcher):
    CMW_MATCHER_NAME: _py_ClassVar[str] = ...
    def __init__(self): ...

class Cmw3ServerExceptionStringThrowableMatcher(AbstractCmw3ServerExceptionStringThrowableMatcher):
    CMW_SERVER_EXCEPTION_MATCHER_NAME: _py_ClassVar[str] = ...
    def __init__(self): ...
    def checkMatching(self, throwable: java.lang.Throwable) -> java.lang.Throwable: ...
