import cern.accsoft.commons.diag.matcher.cmw
import java.lang
import typing


class AbstractFesaStringThrowableMatcher(cern.accsoft.commons.diag.matcher.cmw.AbstractCmwFEStringThrowableMatcher):
    FESA_PROBLEM_DOMAIN: typing.ClassVar[str] = ...
    FESA_HINT_STRING: typing.ClassVar[str] = ...
    def checkMatching(self, throwable: java.lang.Throwable) -> java.lang.Throwable: ...

class FesaMuxWithAllStringThrowableMatcher(AbstractFesaStringThrowableMatcher):
    CMW_IO_FESA_MUX_WITH_ALL_MATCHER_NAME: typing.ClassVar[str] = ...
    def __init__(self): ...

class FesaNoDataStringThrowableMatcher(AbstractFesaStringThrowableMatcher):
    CMW_IO_FESA_NO_DATA_MATCHER_NAME: typing.ClassVar[str] = ...
    def __init__(self): ...

class FesaOutOfRangeStringThrowableMatcher(AbstractFesaStringThrowableMatcher):
    CMW_IO_FESA_OUT_OF_RANGE_MATCHER_NAME: typing.ClassVar[str] = ...
    def __init__(self): ...

class FesaStringThrowableMatcher(AbstractFesaStringThrowableMatcher):
    CMW_IO_FESA_MATCHER_NAME: typing.ClassVar[str] = ...
    def __init__(self): ...
    def checkMatching(self, throwable: java.lang.Throwable) -> java.lang.Throwable: ...
