import cern.japc.core
import java.lang
import java.util
import java.util.concurrent
import typing



class FanoutParameterValueListener(cern.japc.core.ParameterValueListener):
    """
    Java class 'cern.japc.core.spi.util.FanoutParameterValueListener'
    
        Extends:
            java.lang.Object
    
        Interfaces:
            cern.japc.core.ParameterValueListener
    
      Constructors:
        * FanoutParameterValueListener(java.util.Collection)
    
    """
    def __init__(self, collection: typing.Union[java.util.Collection[cern.japc.core.ParameterValueListener], typing.Sequence[cern.japc.core.ParameterValueListener]]): ...
    def exceptionOccured(self, string: str, string2: str, parameterException: cern.japc.core.ParameterException) -> None: ...
    def valueReceived(self, string: str, acquiredParameterValue: cern.japc.core.AcquiredParameterValue) -> None: ...

class JapcExecutor:
    """
    Java class 'cern.japc.core.spi.util.JapcExecutor'
    
        Extends:
            java.lang.Object
    
      Attributes:
        SYSPROP_MAXTHREADS (java.lang.String): final static field
        SYSPROP_BLOCKSTRAT (java.lang.String): final static field
        SYSPROP_BUFSIZE (java.lang.String): final static field
        SYSPROP_INSTRUMENTATION_DISABLED (java.lang.String): final static field
        SYSPROP_INSTRUMENTATION_INTERVAL_SEC (java.lang.String): final static field
        SYSPROP_SCHEDULED_THREADS (java.lang.String): final static field
        BS_ABORT (java.lang.String): final static field
        BS_WAIT (java.lang.String): final static field
        BS_DISCARD (java.lang.String): final static field
    
    """
    SYSPROP_MAXTHREADS: typing.ClassVar[str] = ...
    SYSPROP_BLOCKSTRAT: typing.ClassVar[str] = ...
    SYSPROP_BUFSIZE: typing.ClassVar[str] = ...
    SYSPROP_INSTRUMENTATION_DISABLED: typing.ClassVar[str] = ...
    SYSPROP_INSTRUMENTATION_INTERVAL_SEC: typing.ClassVar[str] = ...
    SYSPROP_SCHEDULED_THREADS: typing.ClassVar[str] = ...
    BS_ABORT: typing.ClassVar[str] = ...
    BS_WAIT: typing.ClassVar[str] = ...
    BS_DISCARD: typing.ClassVar[str] = ...
    def execute(self, runnable: typing.Union[java.lang.Runnable, typing.Callable]) -> None: ...
    @staticmethod
    def get() -> 'JapcExecutor': ...
    def getBlockedExcecutionStrategy(self) -> str: ...
    def getBufferSize(self) -> int: ...
    def getMaximumPoolSize(self) -> int: ...
    def getMinimumPoolSize(self) -> int: ...
    def getPoolSize(self) -> int: ...
    def getRequestBufferMaxSize(self) -> int: ...
    @staticmethod
    def getScheduledExecutor() -> java.util.concurrent.ScheduledExecutorService: ...
    class JmxMBean:
        """
        Java class 'cern.japc.core.spi.util.JapcExecutor$JmxMBean'
        
        """
        def getActiveThreadNumber(self) -> int: ...
        def getCurrentBufferSize(self) -> int: ...
        def getCurrentThreadPoolSize(self) -> int: ...
        def getDeliveredUpdateNumber(self) -> int: ...
        def getDiscardedUpdateNumber(self) -> int: ...
        def getInstrumentationState(self) -> str: ...
        def getMaxBufferSize(self) -> int: ...
        def getMaxThreadPoolSize(self) -> int: ...
        def getRejectedUpdateNumber(self) -> int: ...
        def getSaturationPolicy(self) -> str: ...
        def getSubmittedUpdateNumber(self) -> int: ...

_MultiValueMap__K = typing.TypeVar('_MultiValueMap__K')  # <K>
_MultiValueMap__V = typing.TypeVar('_MultiValueMap__V')  # <V>
class MultiValueMap(typing.Generic[_MultiValueMap__K, _MultiValueMap__V]):
    """
    Java class 'cern.japc.core.spi.util.MultiValueMap'
    
        Extends:
            java.lang.Object
    
      Constructors:
        * MultiValueMap(int, java.lang.Class)
        * MultiValueMap(int)
        * MultiValueMap(java.lang.Class)
        * MultiValueMap()
    
    """
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, int: int): ...
    @typing.overload
    def __init__(self, int: int, class_: typing.Type[java.util.Collection]): ...
    @typing.overload
    def __init__(self, class_: typing.Type[java.util.Collection]): ...
    def clear(self) -> None: ...
    def contains(self, k: _MultiValueMap__K, v: _MultiValueMap__V) -> bool: ...
    def containsAll(self, k: _MultiValueMap__K, collection: typing.Union[java.util.Collection[_MultiValueMap__V], typing.Sequence[_MultiValueMap__V]]) -> bool: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getKeys(self) -> java.util.Set[_MultiValueMap__K]: ...
    def getValues(self, k: _MultiValueMap__K) -> java.util.Collection[_MultiValueMap__V]: ...
    def hashCode(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def put(self, k: _MultiValueMap__K, v: _MultiValueMap__V) -> None: ...
    def putAll(self, k: _MultiValueMap__K, collection: typing.Union[java.util.Collection[_MultiValueMap__V], typing.Sequence[_MultiValueMap__V]]) -> None: ...
    @typing.overload
    def remove(self, k: _MultiValueMap__K) -> bool: ...
    @typing.overload
    def remove(self, k: _MultiValueMap__K, v: _MultiValueMap__V) -> bool: ...
    def removeAll(self, k: _MultiValueMap__K, collection: typing.Union[java.util.Collection[_MultiValueMap__V], typing.Sequence[_MultiValueMap__V]]) -> bool: ...
    def size(self, k: _MultiValueMap__K) -> int: ...
    def toString(self) -> str: ...

class SwingThreadParameterValueListener(cern.japc.core.ParameterValueListener):
    """
    Java class 'cern.japc.core.spi.util.SwingThreadParameterValueListener'
    
        Extends:
            java.lang.Object
    
        Interfaces:
            cern.japc.core.ParameterValueListener
    
      Constructors:
        * SwingThreadParameterValueListener()
    
    """
    def __init__(self): ...
    def exceptionOccured(self, string: str, string2: str, parameterException: cern.japc.core.ParameterException) -> None: ...
    def valueReceived(self, string: str, acquiredParameterValue: cern.japc.core.AcquiredParameterValue) -> None: ...

_SynchronizedMultiValueMap__K = typing.TypeVar('_SynchronizedMultiValueMap__K')  # <K>
_SynchronizedMultiValueMap__V = typing.TypeVar('_SynchronizedMultiValueMap__V')  # <V>
class SynchronizedMultiValueMap(typing.Generic[_SynchronizedMultiValueMap__K, _SynchronizedMultiValueMap__V]):
    """
    Java class 'cern.japc.core.spi.util.SynchronizedMultiValueMap'
    
        Extends:
            java.lang.Object
    
      Constructors:
        * SynchronizedMultiValueMap()
        * SynchronizedMultiValueMap(int)
    
    """
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, int: int): ...
    def clear(self) -> None: ...
    def contains(self, k: _SynchronizedMultiValueMap__K, v: _SynchronizedMultiValueMap__V) -> bool: ...
    def containsAll(self, k: _SynchronizedMultiValueMap__K, collection: typing.Union[java.util.Collection[_SynchronizedMultiValueMap__V], typing.Sequence[_SynchronizedMultiValueMap__V]]) -> bool: ...
    def equals(self, object: typing.Any) -> bool: ...
    def getKeys(self) -> java.util.Set[_SynchronizedMultiValueMap__K]: ...
    def getValues(self, k: _SynchronizedMultiValueMap__K) -> java.util.Collection[_SynchronizedMultiValueMap__V]: ...
    def hashCode(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def put(self, k: _SynchronizedMultiValueMap__K, v: _SynchronizedMultiValueMap__V) -> None: ...
    @typing.overload
    def remove(self, k: _SynchronizedMultiValueMap__K) -> bool: ...
    @typing.overload
    def remove(self, k: _SynchronizedMultiValueMap__K, v: _SynchronizedMultiValueMap__V) -> bool: ...
    def size(self, k: _SynchronizedMultiValueMap__K) -> int: ...
    def toString(self) -> str: ...

class ThreadedParameterValueListener(cern.japc.core.ParameterValueListener):
    """
    Java class 'cern.japc.core.spi.util.ThreadedParameterValueListener'
    
        Extends:
            java.lang.Object
    
        Interfaces:
            cern.japc.core.ParameterValueListener
    
      Constructors:
        * ThreadedParameterValueListener(cern.japc.core.spi.util.JapcExecutor, cern.japc.core.ParameterValueListener)
        * ThreadedParameterValueListener(cern.japc.core.ParameterValueListener)
    
    """
    @typing.overload
    def __init__(self, parameterValueListener: cern.japc.core.ParameterValueListener): ...
    @typing.overload
    def __init__(self, japcExecutor: JapcExecutor, parameterValueListener: cern.japc.core.ParameterValueListener): ...
    def exceptionOccured(self, string: str, string2: str, parameterException: cern.japc.core.ParameterException) -> None: ...
    def valueReceived(self, string: str, acquiredParameterValue: cern.japc.core.AcquiredParameterValue) -> None: ...
    class ValueReceivedCommand(java.lang.Runnable):
        """
        Java class 'cern.japc.core.spi.util.ThreadedParameterValueListener$ValueReceivedCommand'
        
            Extends:
                java.lang.Object
        
            Interfaces:
                java.lang.Runnable
        
        """
        def getValue(self) -> cern.japc.core.AcquiredParameterValue: ...
        def run(self) -> None: ...
        def toString(self) -> str: ...

class TimeUtils:
    """
    Java class 'cern.japc.core.spi.util.TimeUtils'
    
        Extends:
            java.lang.Object
    
    """
    @staticmethod
    def currentTimeNanos() -> int: ...


class __module_protocol__(typing.Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("cern.japc.core.spi.util")``.

    FanoutParameterValueListener: typing.Type[FanoutParameterValueListener]
    JapcExecutor: typing.Type[JapcExecutor]
    MultiValueMap: typing.Type[MultiValueMap]
    SwingThreadParameterValueListener: typing.Type[SwingThreadParameterValueListener]
    SynchronizedMultiValueMap: typing.Type[SynchronizedMultiValueMap]
    ThreadedParameterValueListener: typing.Type[ThreadedParameterValueListener]
    TimeUtils: typing.Type[TimeUtils]
