import cern.japc.core
import cern.japc.core.factory
import cern.japc.value
import java.io
import java.util
import typing



class Descriptors:
    """
    Java class 'cern.japc.core.support.Descriptors'
    
        Extends:
            java.lang.Object
    
      Constructors:
        * Descriptors()
    
      Attributes:
        RDA (java.lang.String): final static field
        RDA3 (java.lang.String): final static field
        DEFAULT_STRING (java.lang.String): final static field
        IS_VALID (java.lang.String): final static field
        ERROR_STRING (java.lang.String): final static field
        SERVER_NAME (java.lang.String): final static field
        DEVICE_ALIAS (java.lang.String): final static field
        RESPONSIBLE (java.lang.String): final static field
        CLASS_VERSION (java.lang.String): final static field
        IMPL_UNKNOWN (java.lang.String): final static field
        IMPL_VIRTUAL (java.lang.String): final static field
        IMPL_HARDWARE (java.lang.String): final static field
        IMPL_SLEQUIP (java.lang.String): final static field
        IMPL_GM (java.lang.String): final static field
        IMPL_FESA (java.lang.String): final static field
        IMPL_FGC (java.lang.String): final static field
        IMPL_BISCOTO (java.lang.String): final static field
        DATA_SOURCE (java.lang.String): final static field
        DATA_SOURCE_UNKNOWN (java.lang.String): final static field
    
    """
    RDA: typing.ClassVar[str] = ...
    RDA3: typing.ClassVar[str] = ...
    DEFAULT_STRING: typing.ClassVar[str] = ...
    IS_VALID: typing.ClassVar[str] = ...
    ERROR_STRING: typing.ClassVar[str] = ...
    SERVER_NAME: typing.ClassVar[str] = ...
    DEVICE_ALIAS: typing.ClassVar[str] = ...
    RESPONSIBLE: typing.ClassVar[str] = ...
    CLASS_VERSION: typing.ClassVar[str] = ...
    IMPL_UNKNOWN: typing.ClassVar[str] = ...
    IMPL_VIRTUAL: typing.ClassVar[str] = ...
    IMPL_HARDWARE: typing.ClassVar[str] = ...
    IMPL_SLEQUIP: typing.ClassVar[str] = ...
    IMPL_GM: typing.ClassVar[str] = ...
    IMPL_FESA: typing.ClassVar[str] = ...
    IMPL_FGC: typing.ClassVar[str] = ...
    IMPL_BISCOTO: typing.ClassVar[str] = ...
    DATA_SOURCE: typing.ClassVar[str] = ...
    DATA_SOURCE_UNKNOWN: typing.ClassVar[str] = ...
    def __init__(self): ...
    @staticmethod
    def getAccelerator(string: str) -> str: ...
    @typing.overload
    @staticmethod
    def getClassVersion(deviceDescriptor: cern.japc.core.DeviceDescriptor) -> str: ...
    @typing.overload
    @staticmethod
    def getClassVersion(string: str) -> str: ...
    @staticmethod
    def getColumnCount(parameter: cern.japc.core.Parameter) -> int: ...
    @staticmethod
    def getDataSource(string: str) -> str: ...
    @staticmethod
    def getDescription(string: str) -> str: ...
    @typing.overload
    @staticmethod
    def getDeviceAlias(deviceDescriptor: cern.japc.core.DeviceDescriptor) -> str: ...
    @typing.overload
    @staticmethod
    def getDeviceAlias(string: str) -> str: ...
    @staticmethod
    def getDeviceClassName(string: str) -> str: ...
    @typing.overload
    @staticmethod
    def getDeviceResponsible(deviceDescriptor: cern.japc.core.DeviceDescriptor) -> str: ...
    @typing.overload
    @staticmethod
    def getDeviceResponsible(string: str) -> str: ...
    @staticmethod
    def getEnumItemSymbols(string: str) -> java.util.Collection[str]: ...
    @staticmethod
    def getEnumType(string: str) -> cern.japc.value.EnumType: ...
    @typing.overload
    @staticmethod
    def getErrors(deviceDescriptor: cern.japc.core.DeviceDescriptor) -> str: ...
    @typing.overload
    @staticmethod
    def getErrors(parameterDescriptor: cern.japc.core.ParameterDescriptor) -> str: ...
    @typing.overload
    @staticmethod
    def getErrors(string: str) -> str: ...
    @staticmethod
    def getFormatPattern(string: str) -> str: ...
    @typing.overload
    @staticmethod
    def getHostName(deviceDescriptor: cern.japc.core.DeviceDescriptor) -> str: ...
    @typing.overload
    @staticmethod
    def getHostName(string: str) -> str: ...
    @staticmethod
    def getImplementation(string: str) -> int: ...
    @staticmethod
    def getImplementationAsString(string: str) -> str: ...
    @staticmethod
    def getLength(string: str) -> int: ...
    @staticmethod
    def getMapPropertyFieldNames(string: str) -> typing.List[str]: ...
    @staticmethod
    def getMaxValue(string: str) -> float: ...
    @staticmethod
    def getMinValue(string: str) -> float: ...
    @staticmethod
    def getRowCount(parameter: cern.japc.core.Parameter) -> int: ...
    @typing.overload
    @staticmethod
    def getServerName(deviceDescriptor: cern.japc.core.DeviceDescriptor) -> str: ...
    @typing.overload
    @staticmethod
    def getServerName(string: str) -> str: ...
    @staticmethod
    def getSettableEnumItemSymbols(string: str) -> java.util.Collection[str]: ...
    @typing.overload
    @staticmethod
    def getSimpleValueDescriptor(valueDescriptor: cern.japc.value.ValueDescriptor, string: str) -> cern.japc.value.SimpleDescriptor: ...
    @typing.overload
    @staticmethod
    def getSimpleValueDescriptor(string: str) -> cern.japc.value.SimpleDescriptor: ...
    @staticmethod
    def getTgmName(string: str) -> str: ...
    @staticmethod
    def getTitle(string: str) -> str: ...
    @staticmethod
    def getType(string: str) -> cern.japc.value.Type: ...
    @staticmethod
    def getUnit(string: str) -> str: ...
    @staticmethod
    def getValueDescriptor(string: str) -> cern.japc.value.MapDescriptor: ...
    @typing.overload
    @staticmethod
    def getValueType(simpleDescriptor: cern.japc.value.SimpleDescriptor) -> cern.japc.value.ValueType: ...
    @typing.overload
    @staticmethod
    def getValueType(string: str) -> cern.japc.value.ValueType: ...
    @staticmethod
    def isAcquisition(parameterDescriptor: cern.japc.core.ParameterDescriptor) -> bool: ...
    @typing.overload
    @staticmethod
    def isConstant(string: str) -> bool: ...
    @typing.overload
    @staticmethod
    def isConstant(valueDescriptor: cern.japc.value.ValueDescriptor) -> bool: ...
    @staticmethod
    def isControl(parameterDescriptor: cern.japc.core.ParameterDescriptor) -> bool: ...
    @staticmethod
    def isCycleBound(string: str) -> bool: ...
    @staticmethod
    def isCycleDependent(string: str) -> bool: ...
    @staticmethod
    def isDefaultString(string: str) -> bool: ...
    @staticmethod
    def isDiscrete(string: str) -> bool: ...
    @staticmethod
    def isFilterable(string: str) -> bool: ...
    @staticmethod
    def isMonitorable(string: str) -> bool: ...
    @staticmethod
    def isMultiplexed(string: str) -> bool: ...
    @staticmethod
    def isNonCycleBoundAcquisition(parameterDescriptor: cern.japc.core.ParameterDescriptor) -> bool: ...
    @staticmethod
    def isReadable(string: str) -> bool: ...
    @staticmethod
    def isTransactional(string: str) -> bool: ...
    @typing.overload
    @staticmethod
    def isValid(deviceDescriptor: cern.japc.core.DeviceDescriptor) -> bool: ...
    @typing.overload
    @staticmethod
    def isValid(parameterDescriptor: cern.japc.core.ParameterDescriptor) -> bool: ...
    @typing.overload
    @staticmethod
    def isValid(valueDescriptor: cern.japc.value.ValueDescriptor) -> bool: ...
    @typing.overload
    @staticmethod
    def isValid(string: str) -> bool: ...
    @staticmethod
    def isWritable(string: str) -> bool: ...

class DiagTrace:
    """
    Java class 'cern.japc.core.support.DiagTrace'
    
        Extends:
            java.lang.Object
    
      Constructors:
        * DiagTrace()
    
      Attributes:
        RDA_SUBSCRIPTION (int): final static field
        RDA_DATA_RECEPTION (int): final static field
        RDA_DATA_SET (int): final static field
        RDA_PARAMETER_CREATION (int): final static field
    
    """
    RDA_SUBSCRIPTION: typing.ClassVar[int] = ...
    RDA_DATA_RECEPTION: typing.ClassVar[int] = ...
    RDA_DATA_SET: typing.ClassVar[int] = ...
    RDA_PARAMETER_CREATION: typing.ClassVar[int] = ...
    def __init__(self): ...
    @staticmethod
    def displayTrace(int: int, string: str) -> None: ...
    @staticmethod
    def getTraceLevel() -> int: ...
    @staticmethod
    def println(string: str, string2: str) -> None: ...
    @staticmethod
    def setTraceLevel(int: int) -> None: ...
    @staticmethod
    def setTraceOutput(printStream: java.io.PrintStream) -> None: ...
    @staticmethod
    def timeStamp() -> str: ...

class FirstUpdateDiscardingPVL(cern.japc.core.ParameterValueListener):
    """
    Java class 'cern.japc.core.support.FirstUpdateDiscardingPVL'
    
        Extends:
            java.lang.Object
    
        Interfaces:
            cern.japc.core.ParameterValueListener
    
      Constructors:
        * FirstUpdateDiscardingPVL(cern.japc.core.ParameterValueListener)
    
    """
    def __init__(self, parameterValueListener: cern.japc.core.ParameterValueListener): ...
    def exceptionOccured(self, string: str, string2: str, parameterException: cern.japc.core.ParameterException) -> None: ...
    def valueReceived(self, string: str, acquiredParameterValue: cern.japc.core.AcquiredParameterValue) -> None: ...

class ParameterCatalog:
    """
    Java class 'cern.japc.core.support.ParameterCatalog'
    
        Extends:
            java.lang.Object
    
      Constructors:
        * ParameterCatalog()
        * ParameterCatalog(cern.japc.core.factory.ParameterFactory)
        * ParameterCatalog(cern.japc.core.factory.ParameterFactory, boolean)
    
    """
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, parameterFactory: cern.japc.core.factory.ParameterFactory): ...
    @typing.overload
    def __init__(self, parameterFactory: cern.japc.core.factory.ParameterFactory, boolean: bool): ...
    def destroy(self) -> None: ...
    def destroyParameter(self, string: str) -> None: ...
    def getParameterDescriptor(self, string: str) -> cern.japc.core.ParameterDescriptor: ...
    @typing.overload
    def getValue(self, string: str, selector: cern.japc.core.Selector) -> cern.japc.core.AcquiredParameterValue: ...
    @typing.overload
    def getValue(self, string: str, selector: cern.japc.core.Selector, parameterValueListener: cern.japc.core.ParameterValueListener) -> None: ...
    def getValueDescriptor(self, string: str) -> cern.japc.value.ValueDescriptor: ...
    def isMonitoring(self, string: str, selector: cern.japc.core.Selector) -> bool: ...
    def newParameter(self, string: str) -> None: ...
    @typing.overload
    def setValue(self, string: str, selector: cern.japc.core.Selector, parameterValue: cern.japc.value.ParameterValue) -> None: ...
    @typing.overload
    def setValue(self, string: str, selector: cern.japc.core.Selector, parameterValue: cern.japc.value.ParameterValue, parameterValueListener: cern.japc.core.ParameterValueListener) -> None: ...
    def startMonitoring(self, string: str, selector: cern.japc.core.Selector, parameterValueListener: cern.japc.core.ParameterValueListener) -> None: ...
    def stopMonitoring(self, string: str, selector: cern.japc.core.Selector) -> None: ...

class ParameterGroupValues:
    """
    Java class 'cern.japc.core.support.ParameterGroupValues'
    
        Extends:
            java.lang.Object
    
    """
    @typing.overload
    @staticmethod
    def checkForException(failSafeParameterValueArray: typing.List[cern.japc.core.FailSafeParameterValue]) -> cern.japc.core.FailSafeParameterValue: ...
    @typing.overload
    @staticmethod
    def checkForException(failSafeParameterValueArray: typing.List[cern.japc.core.FailSafeParameterValue], boolean: bool) -> cern.japc.core.FailSafeParameterValue: ...
    @staticmethod
    def joinSimple2ManyMaps(acquiredParameterValueArray: typing.List[cern.japc.core.AcquiredParameterValue]) -> typing.List[cern.japc.core.AcquiredParameterValue]: ...
    @staticmethod
    def joinSimple2ManyMapsFailSafe(failSafeParameterValueArray: typing.List[cern.japc.core.FailSafeParameterValue]) -> typing.List[cern.japc.core.FailSafeParameterValue]: ...
    @staticmethod
    def joinSimple2OneMap(acquiredParameterValueArray: typing.List[cern.japc.core.AcquiredParameterValue]) -> cern.japc.core.AcquiredParameterValue: ...
    @staticmethod
    def joinSimple2OneMapFailSafe(failSafeParameterValueArray: typing.List[cern.japc.core.FailSafeParameterValue]) -> cern.japc.core.FailSafeParameterValue: ...
    @staticmethod
    def splitOneMap2Simple(acquiredParameterValue: cern.japc.core.AcquiredParameterValue) -> typing.List[cern.japc.core.AcquiredParameterValue]: ...

class ParameterValues:
    """
    Java class 'cern.japc.core.support.ParameterValues'
    
        Extends:
            java.lang.Object
    
    """
    @typing.overload
    @staticmethod
    def extractParameterValue(acquiredParameterValue: cern.japc.core.AcquiredParameterValue) -> typing.Any: ...
    @typing.overload
    @staticmethod
    def extractParameterValue(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, int: int) -> typing.Any: ...
    @typing.overload
    @staticmethod
    def extractParameterValue(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, string: str) -> typing.Any: ...
    @typing.overload
    @staticmethod
    def extractParameterValue(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, string: str, int: int) -> typing.Any: ...
    @staticmethod
    def extractSimpleParameterValue(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, string: str) -> cern.japc.value.SimpleParameterValue: ...
    @typing.overload
    @staticmethod
    def getFieldStatus(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, int: int, string: str) -> cern.japc.value.ValueStatus: ...
    @typing.overload
    @staticmethod
    def getFieldStatus(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, int: int, string: str, int2: int) -> cern.japc.value.ValueStatus: ...
    @typing.overload
    @staticmethod
    def getFieldStatus(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, string: str) -> cern.japc.value.ValueStatus: ...
    @typing.overload
    @staticmethod
    def getFieldStatus(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, string: str, int: int) -> cern.japc.value.ValueStatus: ...
    @typing.overload
    @staticmethod
    def getFieldValue(acquiredParameterValue: cern.japc.core.AcquiredParameterValue) -> str: ...
    @typing.overload
    @staticmethod
    def getFieldValue(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, int: int) -> str: ...
    @typing.overload
    @staticmethod
    def getFieldValue(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, int: int, string: str) -> str: ...
    @typing.overload
    @staticmethod
    def getFieldValue(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, int: int, string: str, int2: int) -> str: ...
    @typing.overload
    @staticmethod
    def getFieldValue(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, string: str) -> str: ...
    @typing.overload
    @staticmethod
    def getFieldValue(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, string: str, int: int) -> str: ...
    @typing.overload
    @staticmethod
    def getFieldValue(failSafeParameterValue: cern.japc.core.FailSafeParameterValue, int: int, string: str) -> str: ...
    @typing.overload
    @staticmethod
    def getFieldValue(failSafeParameterValue: cern.japc.core.FailSafeParameterValue, int: int, string: str, int2: int) -> str: ...
    @typing.overload
    @staticmethod
    def getFieldValue(failSafeParameterValue: cern.japc.core.FailSafeParameterValue, string: str) -> str: ...
    @typing.overload
    @staticmethod
    def getFieldValue(failSafeParameterValue: cern.japc.core.FailSafeParameterValue, string: str, int: int) -> str: ...
    @staticmethod
    def getMaxValue(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, string: str) -> float: ...
    @staticmethod
    def getMinValue(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, string: str) -> float: ...
    @staticmethod
    def getUnit(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, string: str) -> str: ...
    @staticmethod
    def getValueAsBoolean(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, string: str) -> bool: ...
    @staticmethod
    def getValueAsDouble(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, string: str) -> float: ...
    @staticmethod
    def getValueAsFloat(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, string: str) -> float: ...
    @staticmethod
    def getValueAsInt(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, string: str) -> int: ...
    @staticmethod
    def getValueAsLong(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, string: str) -> int: ...
    @staticmethod
    def getValueAsStrings(acquiredParameterValue: cern.japc.core.AcquiredParameterValue, string: str) -> typing.List[str]: ...
    @staticmethod
    def printArray(parameterValueArray: typing.List[cern.japc.value.ParameterValue]) -> None: ...
    @typing.overload
    @staticmethod
    def replaceControlStatus(simpleParameterValue: cern.japc.value.SimpleParameterValue, simpleValueControlStatus: cern.japc.value.SimpleValueControlStatus) -> cern.japc.value.SimpleParameterValue: ...
    @typing.overload
    @staticmethod
    def replaceControlStatus(simpleValueStatus: cern.japc.value.SimpleValueStatus, simpleValueControlStatus: cern.japc.value.SimpleValueControlStatus) -> cern.japc.value.SimpleValueStatus: ...

class SysoutParameterValueListener(cern.japc.core.ParameterValueListener):
    """
    Java class 'cern.japc.core.support.SysoutParameterValueListener'
    
        Extends:
            java.lang.Object
    
        Interfaces:
            cern.japc.core.ParameterValueListener
    
      Constructors:
        * SysoutParameterValueListener()
    
    """
    def __init__(self): ...
    def exceptionOccured(self, string: str, string2: str, parameterException: cern.japc.core.ParameterException) -> None: ...
    def valueReceived(self, string: str, acquiredParameterValue: cern.japc.core.AcquiredParameterValue) -> None: ...


class __module_protocol__(typing.Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("cern.japc.core.support")``.

    Descriptors: typing.Type[Descriptors]
    DiagTrace: typing.Type[DiagTrace]
    FirstUpdateDiscardingPVL: typing.Type[FirstUpdateDiscardingPVL]
    ParameterCatalog: typing.Type[ParameterCatalog]
    ParameterGroupValues: typing.Type[ParameterGroupValues]
    ParameterValues: typing.Type[ParameterValues]
    SysoutParameterValueListener: typing.Type[SysoutParameterValueListener]
