from typing import List as _py_List
from typing import ClassVar as _py_ClassVar
import cern.rbac.common


class TestTokenBuilder:
    DEFAULT_USER_ACCOUNT_TYPE: _py_ClassVar[cern.rbac.common.UserPrincipal.AccountType] = ...
    def application(self, string: str) -> 'TestTokenBuilder': ...
    def authenticationTime(self, int: int) -> 'TestTokenBuilder': ...
    def build(self) -> cern.rbac.common.RbaToken: ...
    def lifeTime(self, int: int) -> 'TestTokenBuilder': ...
    def location(self, string: str) -> 'TestTokenBuilder': ...
    @classmethod
    def newInstance(cls) -> 'TestTokenBuilder': ...
    def reset(self) -> 'TestTokenBuilder': ...
    def roles(self, stringArray: _py_List[str]) -> 'TestTokenBuilder': ...
    def rolesExpirations(self, intArray: _py_List[int]) -> 'TestTokenBuilder': ...
    def rolesHints(self, stringArray: _py_List[str]) -> 'TestTokenBuilder': ...
    def tokenType(self, tokenType: cern.rbac.common.TokenType) -> 'TestTokenBuilder': ...
    def userAccountType(self, accountType: cern.rbac.common.UserPrincipal.AccountType) -> 'TestTokenBuilder': ...
    def userEmail(self, string: str) -> 'TestTokenBuilder': ...
    def userFullName(self, string: str) -> 'TestTokenBuilder': ...
    def username(self, string: str) -> 'TestTokenBuilder': ...
