import typing


class PsbConstants:
    PSB_BENDING_RADIUS: typing.ClassVar[float] = ...
    PSB_MACHINE_RADIUS: typing.ClassVar[float] = ...
    PSB_MACHINE_CIRCUMFERENCE: typing.ClassVar[float] = ...
    PSB_GAMMA_TRANSITION: typing.ClassVar[float] = ...
    def __init__(self): ...
