import java.util.concurrent

class ExecutionService:
    def submit(self, callable: java.util.concurrent.Callable) -> java.util.concurrent.Future: ...

class ExecutionServiceImpl(ExecutionService):
    def __init__(self) -> None: ...
    def submit(self, callable: java.util.concurrent.Callable) -> java.util.concurrent.Future: ...
