import cern.accsoft.commons.diag.matcher
import typing


class AbstractRbacStringThrowableMatcher(cern.accsoft.commons.diag.matcher.StringThrowableMatcher):
    RBAC_PROBLEM_DOMAIN: typing.ClassVar[str] = ...

class RbacCmw3SecurityExceptionStringThrowableMatcher(AbstractRbacStringThrowableMatcher):
    RBAC_CMW_SECURITY_MATCHER_NAME: typing.ClassVar[str] = ...
    def __init__(self): ...

class RbacStringThrowableMatcher(AbstractRbacStringThrowableMatcher):
    RBAC_MATCHER_NAME: typing.ClassVar[str] = ...
    def __init__(self): ...
