from typing import List as _py_List
from typing import ClassVar as _py_ClassVar
from typing import overload


class FloatingPointComparator:
    DOUBLE_TOLERANCE: _py_ClassVar[float] = ...
    FLOAT_TOLERANCE: _py_ClassVar[float] = ...
    def __init__(self): ...
    @classmethod
    @overload
    def compare(cls, double: float, double2: float) -> int: ...
    @classmethod
    @overload
    def compare(cls, float: float, float2: float) -> int: ...
    @classmethod
    @overload
    def equal(cls, float: float, float2: float) -> bool: ...
    @classmethod
    @overload
    def equal(cls, double: float, double2: float) -> bool: ...
    @classmethod
    @overload
    def equal(cls, doubleArray: _py_List[float], doubleArray2: _py_List[float]) -> bool: ...
    @classmethod
    @overload
    def equal(cls, floatArray: _py_List[float], floatArray2: _py_List[float]) -> bool: ...
