import cern.accsoft.commons.util
import cern.japc.core
import cern.japc.core.device
import cern.japc.core.transaction
import java.util


class JapcDeviceImpl(cern.accsoft.commons.util.AbstractNamed[cern.japc.core.device.JapcDevice], cern.japc.core.device.JapcDevice):
    def __init__(self, string: str): ...
    def addParameter(self, immutableParameter: cern.japc.core.ImmutableParameter) -> None: ...
    def getImmutableParameter(self, string: str) -> cern.japc.core.ImmutableParameter: ...
    def getName(self) -> str: ...
    def getParameter(self, string: str) -> cern.japc.core.Parameter: ...
    def getPropertyNames(self) -> java.util.Set[str]: ...
    def getTransactionalParameter(self, string: str) -> cern.japc.core.transaction.TransactionalParameter: ...
    def getWritablePropertyNames(self) -> java.util.Set[str]: ...
