import cern.rbac.common
import java.security
import typing


class TokenSerialization:
    SIGNATURE_LENGTH_SIZE: typing.ClassVar[int] = ...
    TOKEN_LENGTH_SIZE: typing.ClassVar[int] = ...
    SERIAL_ID: typing.ClassVar[str] = ...
    AUTHENTICATION_TIME: typing.ClassVar[str] = ...
    EXPIRATION_TIME: typing.ClassVar[str] = ...
    APPLICATION_NAME: typing.ClassVar[str] = ...
    APPLICATION_CRITICAL: typing.ClassVar[str] = ...
    APPLICATION_TIMEOUT: typing.ClassVar[str] = ...
    LOCATION_NAME: typing.ClassVar[str] = ...
    LOCATION_ADDRESS: typing.ClassVar[str] = ...
    LOCATION_AUTH_REQ: typing.ClassVar[str] = ...
    USER_NAME: typing.ClassVar[str] = ...
    USER_FULLNAME: typing.ClassVar[str] = ...
    USER_EMAIL: typing.ClassVar[str] = ...
    USER_ACCOUNT_TYPE: typing.ClassVar[str] = ...
    USER_ROLES: typing.ClassVar[str] = ...
    USER_ROLES_LIFETIME: typing.ClassVar[str] = ...
    EXTRA_FIELDS: typing.ClassVar[str] = ...
    TOKEN_TYPE: typing.ClassVar[str] = ...
    ROLES_HINT: typing.ClassVar[str] = ...
    ROLES_EXPIRATION: typing.ClassVar[str] = ...
    @staticmethod
    def extractBody(byteArray: typing.List[int]) -> typing.List[int]: ...
    @staticmethod
    def extractSignature(byteArray: typing.List[int]) -> typing.List[int]: ...
    @staticmethod
    def extractSignatureSize(byteArray: typing.List[int]) -> int: ...
    @typing.overload
    @staticmethod
    def getBytes(int: int) -> typing.List[int]: ...
    @typing.overload
    @staticmethod
    def getBytes(string: str) -> typing.List[int]: ...
    @staticmethod
    def sign(privateKey: java.security.PrivateKey, byteArray: typing.List[int]) -> typing.List[int]: ...
    @staticmethod
    def toInt(byteArray: typing.List[int]) -> int: ...
    @typing.overload
    def toString(self) -> str: ...
    @typing.overload
    @staticmethod
    def toString(byteArray: typing.List[int]) -> str: ...
    @staticmethod
    def verifySignature(byteArray: typing.List[int], byteArray2: typing.List[int], rbacConfiguration: cern.rbac.common.RbacConfiguration) -> bool: ...
