from typing import ClassVar as _py_ClassVar


class PsConstants:
    PS_BENDING_RADIUS: _py_ClassVar[float] = ...
    PS_MACHINE_RADIUS: _py_ClassVar[float] = ...
    PS_MACHINE_CIRCUMNFERENCE: _py_ClassVar[float] = ...
    PS_GAMMA_TRANSITION: _py_ClassVar[float] = ...
    def __init__(self): ...
