import typing


class PsConstants:
    PS_BENDING_RADIUS: typing.ClassVar[float] = ...
    PS_MACHINE_RADIUS: typing.ClassVar[float] = ...
    PS_MACHINE_CIRCUMNFERENCE: typing.ClassVar[float] = ...
    PS_GAMMA_TRANSITION: typing.ClassVar[float] = ...
    def __init__(self): ...
