from typing import Any as _py_Any
from typing import ClassVar as _py_ClassVar
import java.io
import java.util
import org.aopalliance.intercept
import org.springframework.remoting.support


class ContextAwareRemoteInvocationExecutor(org.springframework.remoting.support.RemoteInvocationExecutor):
    def __init__(self): ...
    def invoke(self, remoteInvocation: org.springframework.remoting.support.RemoteInvocation, object: _py_Any) -> _py_Any: ...

class ContextAwareRemoteInvocationFactory(org.springframework.remoting.support.RemoteInvocationFactory):
    def __init__(self): ...
    def createRemoteInvocation(self, methodInvocation: org.aopalliance.intercept.MethodInvocation) -> org.springframework.remoting.support.RemoteInvocation: ...
    def getInvocationContextProviders(self) -> java.util.List['InvocationContextProvider']: ...
    def getStaticInvocationContext(self) -> java.util.Map[str, java.io.Serializable]: ...
    def setInvocationContextProviders(self, list: java.util.List['InvocationContextProvider']) -> None: ...
    def setStaticInvocationContext(self, map: java.util.Map[str, java.io.Serializable]) -> None: ...

class InvocationContextProvider:
    def getAttributeMap(self) -> java.util.Map[str, java.io.Serializable]: ...

class RemoteInvocationConstants:
    CTX_CLIENT_ID: _py_ClassVar[str] = ...
    CTX_RBA_TOKEN: _py_ClassVar[str] = ...
    def __init__(self): ...

class ThreadLocalUserContext:
    def __init__(self): ...
    @classmethod
    def clear(cls) -> None: ...
    @classmethod
    def get(cls, string: str) -> java.io.Serializable: ...
    @classmethod
    def put(cls, string: str, serializable: java.io.Serializable) -> None: ...
    @classmethod
    def remove(cls, string: str) -> java.io.Serializable: ...
