import cern.cmw.directory.client
import java.util
import typing


class ServerInfoUtil:
    MAX_SERVICE_URL_LENGTH: typing.ClassVar[int] = ...
    def __init__(self): ...
    @staticmethod
    def getProperties(serverInfo: cern.cmw.directory.client.ServerInfo) -> typing.List[java.util.Properties]: ...
    @staticmethod
    def getServerInfo(propertiesArray: typing.List[java.util.Properties]) -> cern.cmw.directory.client.ServerInfo: ...
