

class EnvironmentResolver:
    @classmethod
    def isDev(cls) -> bool: ...
    @classmethod
    def isNext(cls) -> bool: ...
    @classmethod
    def isPro(cls) -> bool: ...
    @classmethod
    def isTest(cls) -> bool: ...
    @classmethod
    def isTestbed(cls) -> bool: ...
    @classmethod
    def isTwoTier(cls) -> bool: ...
