

class EnvironmentResolver:
    @staticmethod
    def isDev() -> bool: ...
    @staticmethod
    def isNext() -> bool: ...
    @staticmethod
    def isPro() -> bool: ...
    @staticmethod
    def isTest() -> bool: ...
    @staticmethod
    def isTestbed() -> bool: ...
    @staticmethod
    def isTwoTier() -> bool: ...
