import cern.accsoft.commons.util
import cern.accsoft.commons.value
import cern.lsa.domain.commons
import java.util


class FidelModel(cern.accsoft.commons.util.Named, cern.lsa.domain.commons.IdentifiedEntity):
    def findModelCoefficients(self, string: str) -> java.util.Map[str, float]: ...
    def getComponentsNames(self) -> java.util.Set[str]: ...
    def getModelId(self) -> int: ...
    def getModelName(self) -> str: ...

class FieldHarmonic(cern.accsoft.commons.util.Named):
    def getComponentName(self) -> str: ...
    def getCreationDate(self) -> java.util.Date: ...
    def getCurrent2CnFunction(self) -> cern.accsoft.commons.value.ImmutableDiscreteFunction: ...
    def getModelName(self) -> str: ...
    def getName(self) -> str: ...

class MasterControllerTimingEvent(cern.accsoft.commons.util.Named):
    def getTimingParameterName(self) -> str: ...
