import java.io


class RbaReflectiveInvoker:
    def __init__(self): ...
    def clearMiddleTierRbaToken(self) -> None: ...
    def findRbaToken(self) -> java.io.Serializable: ...
    def getHostName(self) -> str: ...
    def getUserName(self) -> str: ...
    def setMiddleTierRbaToken(self, serializable: java.io.Serializable) -> None: ...
