import typing


class SpsConstants:
    SPS_BENDING_RADIUS: typing.ClassVar[float] = ...
    SPS_MACHINE_RADIUS: typing.ClassVar[float] = ...
    SPS_MACHINE_CIRCUMFERENCE: typing.ClassVar[float] = ...
    SPS_GAMMA_TRANSITION: typing.ClassVar[float] = ...
    def __init__(self): ...
