import cern.japc.core
import cern.japc.core.factory
import cern.japc.core.spi
import cern.japc.core.transaction
import cern.japc.value
import java.io
import java.util
import typing


class InternalParameterCharacteristics(cern.japc.core.factory.ParameterCharacteristicsImpl, cern.japc.core.ParameterCharacteristics, java.io.Serializable):
    def __init__(self, parameterCharacteristics: cern.japc.core.ParameterCharacteristics): ...
    def decreaseCreatingCompositeParameter(self) -> None: ...
    def increaseCreatingCompositeParameter(self) -> None: ...
    def isCreatingCompositeParameter(self) -> bool: ...
    def toString(self) -> str: ...

class ParameterCreator:
    SERVICE_NAME_PROPERTY: typing.ClassVar[str] = ...
    PROTOCOL_PROPERTY: typing.ClassVar[str] = ...
    CREATOR_CLASS_PROPERTY: typing.ClassVar[str] = ...
    DEFAULT_PROPERTY: typing.ClassVar[str] = ...
    def createParameter(self, parameterUrl: cern.japc.core.spi.ParameterUrl, parameterDescriptor: cern.japc.core.ParameterDescriptor, valueDescriptor: cern.japc.value.ValueDescriptor, parameterFactory: cern.japc.core.factory.ParameterFactory) -> cern.japc.core.transaction.TransactionalParameter: ...

class ServiceConfigLookup:
    def getConfig(self, string: str) -> typing.List[java.util.Properties]: ...

class AdvancedParameterCreator(ParameterCreator):
    @typing.overload
    def createParameter(self, parameterUrl: cern.japc.core.spi.ParameterUrl, parameterDescriptor: cern.japc.core.ParameterDescriptor, valueDescriptor: cern.japc.value.ValueDescriptor, parameterFactory: cern.japc.core.factory.ParameterFactory, internalParameterCharacteristics: InternalParameterCharacteristics) -> cern.japc.core.transaction.TransactionalParameter: ...
    @typing.overload
    def createParameter(self, parameterUrl: cern.japc.core.spi.ParameterUrl, parameterDescriptor: cern.japc.core.ParameterDescriptor, valueDescriptor: cern.japc.value.ValueDescriptor, parameterFactory: cern.japc.core.factory.ParameterFactory) -> cern.japc.core.transaction.TransactionalParameter: ...

class CompositeParameterCreator(AdvancedParameterCreator):
    def isKnownCompositeParameter(self, parameterUrl: cern.japc.core.spi.ParameterUrl) -> bool: ...
