import cern.japc.core.spi.factory
import java.util
import typing


class LsaNonproEnvironmentServiceConfigLookup(cern.japc.core.spi.factory.ServiceConfigLookup):
    def __init__(self): ...
    def getConfig(self, string: str) -> typing.List[java.util.Properties]: ...
    @staticmethod
    def setServerPropertyFileName(string: str) -> None: ...

class NonproEnvironmentServiceConfigLookup(cern.japc.core.spi.factory.ServiceConfigLookup):
    def __init__(self): ...
    def getConfig(self, string: str) -> typing.List[java.util.Properties]: ...
