from typing import List as _py_List
import cern.japc.core.spi.factory
import java.util


class LsaNonproEnvironmentServiceConfigLookup(cern.japc.core.spi.factory.ServiceConfigLookup):
    def __init__(self): ...
    def getConfig(self, string: str) -> _py_List[java.util.Properties]: ...
    @classmethod
    def setServerPropertyFileName(cls, string: str) -> None: ...

class NonproEnvironmentServiceConfigLookup(cern.japc.core.spi.factory.ServiceConfigLookup):
    def __init__(self): ...
    def getConfig(self, string: str) -> _py_List[java.util.Properties]: ...
