import java.util
import org.w3c.dom


class DomUtils:
    def __init__(self): ...
    @staticmethod
    def getChildElementByTagName(element: org.w3c.dom.Element, string: str) -> org.w3c.dom.Element: ...
    @staticmethod
    def getChildElementValueByTagName(element: org.w3c.dom.Element, string: str) -> str: ...
    @staticmethod
    def getChildElementsByTagName(element: org.w3c.dom.Element, string: str) -> java.util.List: ...
    @staticmethod
    def getTextValue(element: org.w3c.dom.Element) -> str: ...
    @staticmethod
    def nodeNameEquals(node: org.w3c.dom.Node, string: str) -> bool: ...
