import java.util
import org.w3c.dom


class DomUtils:
    def __init__(self): ...
    @classmethod
    def getChildElementByTagName(cls, element: org.w3c.dom.Element, string: str) -> org.w3c.dom.Element: ...
    @classmethod
    def getChildElementValueByTagName(cls, element: org.w3c.dom.Element, string: str) -> str: ...
    @classmethod
    def getChildElementsByTagName(cls, element: org.w3c.dom.Element, string: str) -> java.util.List: ...
    @classmethod
    def getTextValue(cls, element: org.w3c.dom.Element) -> str: ...
    @classmethod
    def nodeNameEquals(cls, node: org.w3c.dom.Node, string: str) -> bool: ...
